var hierarchy =
[
    [ "CaptureImageEvent", "classCaptureImageEvent.html", null ],
    [ "CaptureThread", "classCaptureThread.html", null ],
    [ "Detection::DetectionData", "structDetection_1_1DetectionData.html", null ],
    [ "DMatcher", "classDMatcher.html", null ],
    [ "FeatureDetector", "classFeatureDetector.html", null ],
    [ "FILEH264", "classFILEH264.html", null ],
    [ "FILEWR", "classFILEWR.html", null ],
    [ "Homography", "classHomography.html", null ],
    [ "Detection::HoughData", "structDetection_1_1HoughData.html", null ],
    [ "HoughEvent", "classHoughEvent.html", null ],
    [ "HoughThread", "classHoughThread.html", null ],
    [ "Utils::IDGenerator", "classUtils_1_1IDGenerator.html", null ],
    [ "ImageData", "structImageData.html", null ],
    [ "Detection::Line", "structDetection_1_1Line.html", null ],
    [ "LineDetection", "classLineDetection.html", null ],
    [ "LoadCaptureThread", "classLoadCaptureThread.html", null ],
    [ "LoadFileThread", "classLoadFileThread.html", null ],
    [ "Detection::ObjectDetection", "classDetection_1_1ObjectDetection.html", null ],
    [ "Detection::OFPoint", "structDetection_1_1OFPoint.html", null ],
    [ "Detection::OpticalFlowData", "structDetection_1_1OpticalFlowData.html", null ],
    [ "ProcessThread", "classProcessThread.html", null ],
    [ "ResultThread", "classResultThread.html", null ],
    [ "SpeedCalcEvent", "classSpeedCalcEvent.html", null ],
    [ "SpeedCalculation", "classSpeedCalculation.html", null ],
    [ "SpeedData", "structSpeedData.html", null ],
    [ "SpeedThread", "classSpeedThread.html", null ],
    [ "Task", "classTask.html", [
      [ "CaptureTask", "classCaptureTask.html", null ],
      [ "FlowTask", "classFlowTask.html", null ],
      [ "HoughTask", "classHoughTask.html", null ],
      [ "LoadTask", "classLoadTask.html", null ],
      [ "SiftTask", "classSiftTask.html", null ],
      [ "SpeedTask", "classSpeedTask.html", null ]
    ] ],
    [ "TaskProperty", "structTaskProperty.html", null ],
    [ "ThreadPool", "classThreadPool.html", null ],
    [ "UpdateImageEvent", "classUpdateImageEvent.html", null ]
];