var searchData=
[
  ['savedatathread_0',['SaveDataThread',['../classSaveDataThread.html',1,'']]],
  ['scale_20invariant_20feature_20transform_20sift_1',['Scale Invariant Feature Transform (SIFT)',['../md_Docs_2markdown_2ImageAllignment.html#autotoc_md38',1,'']]],
  ['scp_2',['SpeedCameraPi(SCP)',['../index.html',1,'']]],
  ['script_3',['script',['../md_Docs_2markdown_2InstallingRequiredDependency.html#autotoc_md7',1,'Explanation of script'],['../md_Docs_2markdown_2InstallingRequiredDependency.html#autotoc_md9',1,'Explanation of script'],['../md_Docs_2markdown_2InstallingRequiredDependency.html#autotoc_md11',1,'Explanation of script'],['../md_Docs_2markdown_2InstallingRequiredDependency.html#autotoc_md13',1,'Explanation of script']]],
  ['scripts_4',['Utility Scripts',['../md_Docs_2markdown_2InstallingRequiredDependency.html#autotoc_md15',1,'']]],
  ['selection_20parameter_5',['Line Selection Parameter',['../md_Docs_2markdown_2UsingTheApp.html#autotoc_md28',1,'']]],
  ['sensor_20parameter_6',['Sensor Parameter',['../md_Docs_2markdown_2UsingTheApp.html#autotoc_md25',1,'']]],
  ['setting_20up_20the_20config_20file_7',['Setting up the Config file',['../md_Docs_2markdown_2UsingTheApp.html#autotoc_md21',1,'']]],
  ['setup_8',['Development Setup',['../md_Docs_2markdown_2developmentSetup.html',1,'']]],
  ['setup_20cross_20compilation_9',['Steps to setup Cross-Compilation',['../md_Docs_2markdown_2developmentSetup.html#autotoc_md60',1,'']]],
  ['sift_10',['Scale Invariant Feature Transform (SIFT)',['../md_Docs_2markdown_2ImageAllignment.html#autotoc_md38',1,'']]],
  ['slope_11',['Slope',['../structLine.html#a2d18aef2f7e4ddeb9aebe3cf5a23eb19',1,'Line']]],
  ['speed_20calculation_12',['speed calculation',['../md_Docs_2markdown_2SpeedCalculation.html',1,'Speed Calculation'],['../md_Docs_2markdown_2SpeedCalculation.html#autotoc_md55',1,'Speed Calculation']]],
  ['speedcalculation_2ecpp_13',['speedCalculation.cpp',['../speedCalculation_8cpp.html',1,'']]],
  ['speedcalculation_2ehpp_14',['speedCalculation.hpp',['../speedCalculation_8hpp.html',1,'']]],
  ['speedcamerapi_20project_15',['speedcamerapi project',['../md_Docs_2markdown_2developmentSetup.html#autotoc_md65',1,'Opening SpeedCameraPi project'],['../md_Docs_2markdown_2developmentSetup.html#autotoc_md74',1,'Opening SpeedCameraPi project']]],
  ['speedcamerapi_20scp_16',['SpeedCameraPi(SCP)',['../index.html',1,'']]],
  ['speedtask_17',['speedtask',['../classSpeedTask.html#a0f9dfc0085d49f451caedcd52a80e8ba',1,'SpeedTask::SpeedTask()'],['../classSpeedTask.html',1,'SpeedTask']]],
  ['startup_18',['Startup',['../md_Docs_2markdown_2InstallingRequiredDependency.html#autotoc_md17',1,'']]],
  ['steps_20to_20setup_20cross_20compilation_19',['Steps to setup Cross-Compilation',['../md_Docs_2markdown_2developmentSetup.html#autotoc_md60',1,'']]],
  ['studio_20code_20',['studio code',['../md_Docs_2markdown_2developmentSetup.html#autotoc_md63',1,'Accesing WSL from Visual Studio Code'],['../md_Docs_2markdown_2developmentSetup.html#autotoc_md62',1,'Installing Visual Studio Code']]],
  ['system_21',['Preparing the system',['../md_Docs_2markdown_2InstallingRequiredDependency.html#autotoc_md6',1,'']]]
];
