#pragma once

enum PanelID {
    PANEL_NONE,
    PANEL_CAPTURE,
    PANEL_ROI,
    PANEL_LANE_CALIBRATION,
    PANEL_LANE_MANUAL_CALIBRATION,
    PANEL_DISTANCE_CALIBRATION,
    PANEL_COLOR_CALIBRATION,
    PANEL_TRIM_DATA,
    PANEL_RESULT,
    PANEL_SETTINGS,
    PANEL_INFO
};

enum Mode { MODE_LANE, MODE_DISTANCE };

enum ButtonState { NORMAL, ACTIVE, DISABLED, ON, OFF, HIDDEN };

enum PanelState { PANEL_NOT_OK, PANEL_OK, PANEL_HIDDEN };