#ifndef PROCESS_IMAGE_EVENT_HPP
#define PROCESS_IMAGE_EVENT_HPP

#include <wx/event.h>

wxDECLARE_EVENT(c_PROCESS_IMAGE_EVENT, wxCommandEvent);

enum PROCESS_IMAGE_TYPE { PROCESS_BEGIN = 1, PROCESS_END, PROCESS_ERROR };

#endif