#pragma once

/**
 * @brief Thread ID
 *
 */
enum ThreadID {
    THREAD_NONE,
    THREAD_CAMERA_PREVIEW,
    THREAD_CAPTURE_PREVIEW,
    THREAD_LOAD_CAPTURE,
    THREAD_LOAD_FILE,
    THREAD_SAVE_FILE,
    THREAD_LANE_CALIBRATION_CAMERA,
    THREAD_LANE_CALIBRATION_CAPTURE,
    THREAD_LANE_MANUAL_CALIBRATION_CAMERA,
    THREAD_LANE_MANUAL_CALIBRATION_CAPTURE,
    THREAD_DISTANCE_CALIBRATION_CAMERA,
    THREAD_DISTANCE_CALIBRATION_CAPTURE,
    THREAD_CALIBRATION_PREVIEW_CAMERA,
    THREAD_CALIBRATION_PREVIEW_CAPTURE,
    THREAD_COLOR_CALIBRATION,
    THREAD_COLOR_CALIBRATION_PREVIEW,
    THREAD_ROI,
    THREAD_ROI_PREVIEW,
    THREAD_PROCESS,
    THREAD_RESULT_PREVIEW,
    THREAD_TRIM_DATA,
};