#include "UI/Data/Data.hpp"
#include "UI/Data/Theme.hpp"
#include "Utils/Enum.hpp"
#include <UI/Control/SpinControl/SpinControl.hpp>
#include <wx/gtk/stattext.h>
#include <wx/gtk/textctrl.h>

/**
 * @brief Construct a new Spin Control< T>:: Spin Control object
 *
 * @param parent Pointer to the parent window
 * @param id ID of the spin control
 * @param value Value of the spin control
 */
template <typename T>
SpinControl<T>::SpinControl(wxWindow *parent, wxWindowID id, T value)
    : wxPanel(parent, id), value(value) {
    plusButton =
        new BitmapButtonT3(this, Enum::G_Plus_Button_ID, Data::BitmapT3Plus);
    minusButton =
        new BitmapButtonT3(this, Enum::G_Minus_Button_ID, Data::BitmapT3Minus);

    textCtrl =
        new wxTextCtrl(this, wxID_ANY, std::to_string(value), wxDefaultPosition,
                       wxDefaultSize, wxTE_READONLY | wxTE_CENTRE);

    spacer1 = new wxStaticText(this, wxID_ANY, "", wxDefaultPosition,
                               wxDefaultSize, wxALIGN_CENTER);
    spacer2 = new wxStaticText(this, wxID_ANY, "", wxDefaultPosition,
                               wxSize(100, 40));

    mainSizer = new wxBoxSizer(wxHORIZONTAL);
    mainSizer->Add(spacer1, 1, wxALIGN_CENTER_VERTICAL);
    mainSizer->Add(minusButton, 0, wxRIGHT, 5);
    mainSizer->Add(textCtrl, 2, wxEXPAND | wxRIGHT | wxLEFT, 5);
    mainSizer->Add(plusButton, 0, wxLEFT, 5);
    mainSizer->Add(spacer2, 1, wxALIGN_CENTER_VERTICAL);

    SetSizer(mainSizer);

    // Bind Events
    Bind(wxEVT_BUTTON, &SpinControl<T>::OnPlusButton, this,
         Enum::G_Plus_Button_ID);
    Bind(wxEVT_BUTTON, &SpinControl<T>::OnMinusButton, this,
         Enum::G_Minus_Button_ID);
}

/**
 * @brief Set the text of the spin control
 *
 * @param text Text to set to
 */
template <typename T>
void SpinControl<T>::setText(const wxString &text) {
    spacer1->SetLabelText(text);
}

/**
 * @brief Get the value of the spin control
 *
 * @return T Value of the spin control
 */
template <typename T>
T SpinControl<T>::getValue() {
    return value;
}

/**
 * @brief Set the value of the spin control
 *
 * @param value Value to set to
 */
template <typename T>
void SpinControl<T>::setValue(T value) {
    this->value = value;
    textCtrl->SetValue(std::to_string(value));
}

/**
 * @brief Set the minimum value of the spin control
 *
 * @param minValue Minimum value to set to
 */
template <typename T>
void SpinControl<T>::setMinValue(T minValue) {
    this->minValue = minValue;
}

/**
 * @brief Set the maximum value of the spin control
 *
 * @param maxValue Maximum value to set to
 */
template <typename T>
void SpinControl<T>::setMaxValue(T maxValue) {
    this->maxValue = maxValue;
}

/**
 * @brief Set the increment of the spin control
 *
 * @param increment Increment to set to
 */
template <typename T>
void SpinControl<T>::setIncrement(T increment) {
    this->increment = increment;
}

/**
 * @brief Set the spin data of the spin control
 *
 * @param SpinControlData Spin data to set to
 */
template <typename T>
void SpinControl<T>::setSpinData(const SpinControlData<T> &data) {
    minValue = data.minValue;
    maxValue = data.maxValue;
    increment = data.increment;

    data.isDisabled ? setDisabled() : setEnabled();
}

/**
 * @brief Event handler for the plus button
 *
 * @param e Event generated by the button
 */
template <typename T>
void SpinControl<T>::OnPlusButton(wxCommandEvent &e) {
    if (value < maxValue) {
        T newValue = value + increment;
        value = newValue > maxValue ? maxValue : newValue;
        textCtrl->SetValue(std::to_string(value));
    }

    e.Skip();
}

/**
 * @brief Event handler for the minus button
 *
 * @param e Event generated by the button
 */
template <typename T>
void SpinControl<T>::OnMinusButton(wxCommandEvent &e) {
    if (value > minValue) {
        T newValue = value - increment;
        value = newValue < minValue ? minValue : newValue;
        textCtrl->SetValue(std::to_string(value));
    }

    e.Skip();
}

template class SpinControl<int>;    // Explicit instantiation for int
template class SpinControl<double>; // Explicit instantiation for double
